### ISSUE TITLE
Better to use different route with default static

### ISSUE THREAD

**Issue by fdddf** [TkTech/flask-themer#2]
Some static files like fonts, uploaded images, robots.txt are also store in 'static' directory. 
With flask-themer, these files break to show as 404.

And there is solution, modify the theme blueprint route like this:
```
@theme_blueprint.route('/theme/<theme>/<path:filename>', endpoint='theme')
```
There it works.

**Comment by jeremyh** [comment]
Thanks for fixing this @TkTech!

I noticed this bug is still in the current pypi release, is it possible to get a new release made?

**Comment by TkTech** [comment]
Absolutely, sorry about that. Will throw up a release after work.

**Comment by TkTech** [comment]
Done!

**Comment by jeremyh** [comment]
Thanks Tyler :)
