### ISSUE TITLE
Extend a template from another theme

### ISSUE THREAD

**Issue by azmeuk** [TkTech/flask-themer#3]
In order to slightly adapt another theme without having to copy it all, this would be nice to be able to extend a template from another theme. For example with something like:

```html
{% extends theme('base.html', theme='myothertheme') %}
```

What do you think?

**Comment by TkTech** [comment]
A patch to do this would be accepted, it's a good idea. It should use the same template resolution logic as a normal theme lookup so that it defaults properly when the  desired theme is missing.

**Comment by azmeuk** [comment]
Thank you for having reviewed my PR.
Do you plan to cut a release soon?

**Comment by TkTech** [comment]
I'm currently in the north korean DMZ so it might take a few days :) there are test fixes that are required as werkzeug has dropped 3.7 support.

**Comment by azmeuk** [comment]
Hi. Do you need some help with those test fixes?

**Comment by TkTech** [comment]
Released!
